import type { JobKind } from './types.ts';
export const organizeModes = ['audit', 'docs', 'agents', 'ci'] as const;
export type OrganizeMode = typeof organizeModes[number];
export const organizeActions: Record<OrganizeMode, {title:string; description:string; kind:JobKind; instructions:string}> = {
  audit: {title:'检查文档与仓库结构',description:'查找失配、缺失、重复与职责混乱，先给证据和调整方案。',kind:'investigate',instructions:'Repository organization AUDIT. Do not modify any files. Inventory documentation by audience, responsibility and applicable version. Trace claims to code/configuration. Distinguish factual contradictions, missing essential instructions, optional editorial improvements and intentional historical/design documents. Report exact paths, evidence, impact and smallest proposed correction. Include a document responsibility map in facts. Do not judge complexity by length alone or require every repository to create the same files. No issues found is valid. Never delete or reorganize files during an audit.'},
  docs: {title:'同步与补齐文档',description:'根据实际实现修正文档和示例，保留项目原有风格。',kind:'docs',instructions:'Repository documentation maintenance. Trace each changed claim to implementation/configuration at the pinned revision. For a PR, focus on its actual base/head diff and public behavior changes; internal refactors may need no documentation. Correct evidenced drift, missing essential setup and broken references. Preserve historical proposals and localization. Do not perform broad moves/deletions or architectural restructuring without an explicit accepted plan in handoff/instructions. Validate links/examples using declared checks. No changes needed is a successful assessment, not a reason to manufacture a patch.'},
  agents: {title:'生成 / 更新 AGENTS.md',description:'提取仓库导航、实际命令和开发约定，保留已有人工指引。',kind:'docs',instructions:'Generate or incrementally update AGENTS.md from repository evidence. Read existing root and scoped instructions and CONTRIBUTING first. Keep concise navigation, module boundaries, actual build/test commands with cwd, generated files and demonstrated constraints. Link existing docs instead of copying them. Preserve human conventions; flag conflicts rather than overwriting. Do not invent standards, tool support or claim unexecuted commands are verified. Nested guidance only when module-specific differences justify it. Never grant permissions, disable protections or insert generic role prompting. No change needed is valid.'},
  ci: {title:'配置 / 修复 GitHub CI',description:'沿用现有命令生成基础检查，区分本地验证与远端运行。',kind:'fix',instructions:'Prepare GitHub CI for this repository. Inspect manifests, lockfiles, existing workflows, contribution docs and supported environments. Prefer a minimal lint/test/build workflow using established commands, deterministic dependency installation and compatible runners. Preserve existing workflows and avoid duplicate checks. Use least privileges (normally contents: read), no deployment, secret creation, branch-setting mutation, pull_request_target executing untrusted PR code, or publishing permissions. Do not claim remote CI passed from generated YAML or local tests. Validate syntax and run suitable existing checks within host permissions; describe unavailable prerequisites. External actions must have verified upstream identity/version; do not invent SHAs. No unnecessary changes if checks already cover the need.'}
};
