import React, { useState } from 'react';
import type { Issue } from '../core/types.ts';
import { remoteBlockers, type ActionsLog } from '../core/remote-progress.ts';
import type { WorkflowAction } from './IssuePlanning.tsx';
export function RemoteProgress({issue,busy,act}:{issue:Issue;busy:boolean;act:WorkflowAction}) {
  const [log,setLog]=useState<ActionsLog>(),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  if(issue.type!=='pr' && !issue.linkedPullRequests?.length) return null;
  const actions=issue.actions;
  const read=async(jobId:number)=>{setLoading(true);setError('');setLog(undefined);try{const response=await fetch(`/maintainer/api/actions/log?issueId=${encodeURIComponent(issue.id)}&jobId=${jobId}`);const data=await response.json();if(!response.ok) throw Error(data.error ?? '日志读取失败');setLog(data);}catch(e){setError(e instanceof Error ? e.message:'日志读取失败');}finally{setLoading(false);}};
  return <section className="mw-remote-progress" aria-label="远端交付进度"><h4>远端交付进度</h4><button className="mw-button" disabled={busy} onClick={()=>void act('/remote/sync',{issueId:issue.id},'已刷新 PR 与 Issue 远端进度')}>刷新关联 PR 进度</button>{issue.remoteWarning && <p className="mw-callout amber">{issue.remoteWarning}</p>}
    {!issue.remotePRs?.length && <p>尚未读取远端进度，请刷新。创建 PR 不代表事项已完成。</p>}
    {issue.remotePRs?.map(pr=><article className="mw-finding" key={pr.url}><a href={pr.url} target="_blank" rel="noreferrer">关联 PR #{pr.number || '未知'}</a><p>审查：{pr.review ?? '未知'} · 合并：{pr.mergedAt ? '已合并':pr.mergeState} · {issue.type==='issue'?'Issue':'PR'}：{issue.state==='closed'?'已关闭':'仍开放'}</p><ul>{remoteBlockers(pr,issue.type==='issue' ? issue.state : undefined).map(reason=><li key={reason}>{reason}</li>)}</ul><p>最近成功同步：{pr.syncedAt ? new Date(pr.syncedAt).toLocaleString('zh-CN'):'尚无成功快照'}</p><p>执行版本：<code>{pr.headSha || '未知'}</code></p>{pr.closingIssues.length>0 && <p>GitHub 关联关闭事项：{pr.closingIssues.map(url=><a key={url} href={url} target="_blank" rel="noreferrer">{url} </a>)}</p>}{pr.checks.map((check,i)=><p key={i}>{check.name}：{check.conclusion ?? check.status}</p>)}<button className="mw-button" disabled={busy || !pr.number || !!pr.error} onClick={()=>{setLog(undefined);void act('/actions/sync',{issueId:issue.id,number:pr.number},'已读取当前提交的 Actions 执行与失败步骤');}}>读取 PR #{pr.number} Actions</button></article>)}
    {issue.type==='pr' && !issue.remotePRs?.length && <button className="mw-button" disabled={busy} onClick={()=>void act('/actions/sync',{issueId:issue.id},'已读取 Actions')}>读取 Actions 执行</button>}
    {actions && <details open><summary>Actions 证据 · PR #{actions.prNumber ?? issue.number}</summary>{issue.remotePRs?.some(pr=>pr.number===(actions.prNumber ?? issue.number) && pr.headSha!==actions.headSha) && <p className="mw-callout amber">Actions 属于旧提交，请重新读取当前 PR 的执行。</p>}<p>提交 <code>{actions.headSha}</code> · {new Date(actions.syncedAt).toLocaleString('zh-CN')}</p>{actions.warnings.map(w=><p className="mw-callout amber" key={w}>{w}</p>)}{!actions.jobs.length && <p>未读取到此提交的 Actions job；不代表 CI 通过。合并测试提交或其他 CI 平台可能不在本次覆盖内。</p>}{actions.jobs.map(job=><article className="mw-finding" key={`${job.id}:${job.attempt}`}><a href={job.url} target="_blank" rel="noreferrer">{job.name}</a><p>run {job.runId} · 第 {job.attempt} 次 · job {job.id} · {job.conclusion ?? job.status}</p>{job.steps.filter(step=>step.conclusion && !['success','skipped'].includes(step.conclusion)).map(step=><p key={step.number}>步骤 {step.number}：{step.name} · {step.conclusion}</p>)}<button className="mw-button" disabled={busy || loading} onClick={()=>void read(job.id)}>读取 job {job.id} 日志</button></article>)}<p className="mw-muted">代码回归、环境失败和不稳定测试需结合日志判断；单次失败不能确认不稳定，重跑成功不代表修复。</p></details>}
    {error && <p className="mw-callout amber">{error}</p>}{log && <details open className="mw-execution-evidence"><summary>原始 Actions 日志 · job {log.jobId}</summary><p>run {log.runId} · 第 {log.attempt} 次 · 提交 <code>{log.headSha}</code></p>{log.truncated && <p>日志已裁剪，仅展示前 512 KiB。</p>}<pre>{log.text}</pre></details>}
  </section>;
}
