import React, { useState } from 'react';
import type { FindingFollowup, Job, ReviewThread } from '../core/types.ts';
import type { WorkflowAction } from './IssuePlanning.tsx';

const followupNames = { resolved: '已修复', still_present: '仍存在', unverified: '无法验证' };
function FollowupRow({ job, source, value, disabled, act }: { job: Job; source?: Job; value: FindingFollowup; disabled: boolean; act: WorkflowAction }) {
  const [status, setStatus] = useState(value.status), [evidence, setEvidence] = useState(value.evidence);
  const finding = source?.artifact?.stage === 'review' ? source.artifact.findings.find(f => f.id === value.findingId) : undefined;
  return <article className="mw-finding"><strong>{finding?.title ?? value.findingId} · {followupNames[value.status]}</strong><p>来源审查 <code>{value.sourceJobId}</code> · {finding?.path ?? '来源位置未提供'}</p><p>本次复核：{value.evidence}</p><p className="mw-muted">复核结论来自本次报告或维护者判断，不会自动解决 GitHub 讨论串。</p><label>当前版本复核<select aria-label="当前版本复核" disabled={disabled} value={status} onChange={event => setStatus(event.target.value as FindingFollowup['status'])}>{Object.entries(followupNames).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>当前版本证据或无法验证的原因<textarea aria-label="当前版本证据或无法验证的原因" rows={2} value={evidence} disabled={disabled} onChange={event => setEvidence(event.target.value)} /></label><button className="mw-button" disabled={disabled || !evidence.trim()} onClick={() => void act('/finding-followup', { id: job.id, sourceJobId: value.sourceJobId, findingId: value.findingId, status, evidence }, '已记录当前版本复核，需重新接受审查')}>保存复核</button></article>;
}
type ThreadPreview = { stamp: string; thread: ReviewThread; resolved: boolean; headSha: string; baseSha: string };
export function ReviewFindingControls({ job, history, busy, act }: { job: Job; history: Job[]; busy: boolean; act: WorkflowAction }) {
  const [selected, setSelected] = useState<string[]>([]), [decision, setDecision] = useState('accepted');
  const [preview, setPreview] = useState<ThreadPreview>();
  if (job.artifact?.stage !== 'review') return null;
  const disabled = busy || job.artifactState === 'stale' || job.publications?.review?.status === 'published' || !['completed','awaiting_review','approved'].includes(job.status);
  const threads = job.reviewThreads;
  return <section aria-label="发现复核与讨论串">
    {job.artifact.findings.length > 0 && <details><summary>批量处置审查发现</summary>{job.artifact.findings.map(finding => <label key={finding.id}><input type="checkbox" disabled={disabled} checked={selected.includes(finding.id)} onChange={event => setSelected(values => event.target.checked ? [...values, finding.id] : values.filter(id => id !== finding.id))} />{finding.severity} · {finding.title}</label>)}<label>批量处置<select aria-label="批量处置" value={decision} disabled={disabled} onChange={event => setDecision(event.target.value)}><option value="accepted">接受，交给实施</option><option value="needs_evidence">需要更多证据</option><option value="dismissed">不适用</option><option value="resolved">已解决（维护者判断）</option></select></label><button className="mw-button" disabled={disabled || !selected.length} onClick={async () => { if (await act('/findings', { id: job.id, findingIds: selected, decision }, '已批量保存发现处置')) setSelected([]); }}>应用到 {selected.length} 项发现</button></details>}
    <h4>历史发现的当前版本复核</h4>
    {job.findingFollowups?.length ? job.findingFollowups.map(value => <FollowupRow key={`${job.id}:${value.sourceJobId}:${value.findingId}:${value.status}:${value.evidence}`} job={job} source={history.find(source => source.id === value.sourceJobId)} value={value} disabled={disabled} act={act} />) : <p className="mw-muted">本次没有已关联的历史发现；旧报告未被自动认定为已修复。</p>}
    {job.issueSnapshot.type === 'pr' && <details><summary>GitHub 讨论串状态</summary><button className="mw-button" disabled={busy} onClick={async () => { setPreview(undefined); await act('/threads/sync', { id: job.id }, '已只读同步 GitHub 讨论串'); }}>同步讨论串</button>
      {threads && <><p>同步版本 <code>{threads.headSha}</code> · {threads.syncedAt}</p>{threads.partial && <p className="mw-callout amber">只显示前 100 条讨论串，不能据此判定所有讨论均已解决。</p>}{job.prContext && (threads.headSha !== job.prContext.headSha || threads.baseSha !== job.prContext.baseSha) && <p className="mw-callout amber">讨论串属于另一 PR 版本，请重新审查后再修改远端状态。</p>}{threads.threads.map(thread => <article className="mw-finding" key={thread.id}><strong>{thread.path}{thread.line ? `:${thread.line}` : ''} · {thread.isResolved ? 'GitHub 已解决' : 'GitHub 未解决'}{thread.isOutdated ? ' · 位置已过期' : ''}</strong><p>{thread.body}</p>{thread.url && <a href={thread.url} target="_blank" rel="noreferrer">查看 GitHub 讨论</a>}<label>关联本地发现<select aria-label="关联本地发现" disabled={disabled} value={Object.entries(job.findingThreadLinks ?? {}).find(([, id]) => id === thread.id)?.[0] ?? ''} onChange={event => void act('/threads/link', { id: job.id, findingId: event.target.value, threadId: thread.id }, '已保存显式讨论串关联')}><option value="" disabled>未关联</option>{job.artifact?.stage === 'review' && job.artifact.findings.map(finding => <option value={finding.id} key={finding.id}>{finding.title}</option>)}</select></label><button className="mw-button" disabled={disabled || (thread.isResolved ? !thread.viewerCanUnresolve : !thread.viewerCanResolve)} onClick={async () => { const result = await act('/threads/preview', { id: job.id, threadId: thread.id, resolved: !thread.isResolved }, '已只读核对讨论串，尚未修改 GitHub'); if (result) setPreview(result as ThreadPreview); }}>预览{thread.isResolved ? '重新打开' : '解决'}讨论串</button></article>)}</>}
      {preview && <section className="mw-callout amber" aria-label="讨论串操作确认"><div><strong>确认修改 GitHub 讨论串</strong><p>{preview.thread.path} · {preview.thread.body}</p><p>目标：{preview.resolved ? '标记为已解决' : '重新打开'} · PR head <code>{preview.headSha}</code></p><button className="mw-button" disabled={disabled} onClick={async () => { const current = preview; setPreview(undefined); await act('/threads/update', { id: job.id, threadId: current.thread.id, resolved: current.resolved, stamp: current.stamp }, 'GitHub 已确认讨论串状态'); }}>确认修改远端讨论串</button><button className="mw-text-button" disabled={busy} onClick={() => setPreview(undefined)}>取消</button></div></section>}
    </details>}
  </section>;
}
